const express=require("express")
const db=require("./Database")
const cors=require("cors")
const manage_asset=require("./Admin/manage_assets")
const book_assets=require("./User/book_assets")
const userlogin=require('./User/userlogin')
const app=express()
app.use(express.json())
app.use(cors());
app.use(userlogin)
app.use(manage_asset)
app.use(book_assets)
app.listen(3000,()=>{
    console.log("Server running at port 3000")
})